# Generated by Django 3.2 on 2021-04-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria Produto',
                'verbose_name_plural': 'Categorias Produtos',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('apelido', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=10)),
                ('tamanho', models.CharField(max_length=10)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('composicao', models.CharField(blank=True, max_length=255, null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('preco_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('taxa_desc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('taxa_desc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promocao', models.BooleanField(default=False)),
                ('estoque_saldo', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_pagamento', models.CharField(choices=[('DI', 'Dinheiro'), ('CC', 'Cartão Crédito'), ('CD', 'Cartão Débito'), ('PX', 'Pix'), ('CL', 'Crediário')], max_length=2)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_parcelas', models.IntegerField(blank=True, null=True)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxa_devedor', models.IntegerField(blank=True, default=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'venda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VendaItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venda')),
            ],
            options={
                'verbose_name': 'Venda Item',
                'verbose_name_plural': 'Vendas Itens',
                'db_table': 'venda_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCateriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaproduto')),
            ],
            options={
                'verbose_name': 'Subcategoria Produto',
                'verbose_name_plural': 'Subcategorias Produtos',
                'db_table': 'sub_categoria',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcateriaproduto'),
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('numero', models.CharField(max_length=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_parcial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_venc', models.DateField()),
                ('situacao', models.CharField(choices=[('PG', 'Pago'), ('PP', 'Pago parcial')], max_length=2)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.venda')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'db_table': 'parcela',
                'ordering': ['id'],
            },
        ),
    ]
